package es.pedrazamiguez.splittrip.core.designsystem.presentation.extensions

import es.pedrazamiguez.splittrip.core.common.R
import es.pedrazamiguez.splittrip.domain.enums.ExpenseSubcategory

private val subcategoryToStringResMap: Map<ExpenseSubcategory, Int> = mapOf(
    ExpenseSubcategory.INTERNATIONAL_FLIGHT to R.string.expense_subcategory_international_flight,
    ExpenseSubcategory.DOMESTIC_FLIGHT to R.string.expense_subcategory_domestic_flight,
    ExpenseSubcategory.TRAIN to R.string.expense_subcategory_train,
    ExpenseSubcategory.BUS to R.string.expense_subcategory_bus,
    ExpenseSubcategory.TAXI_RIDESHARE to R.string.expense_subcategory_taxi_rideshare,
    ExpenseSubcategory.PRIVATE_TRANSFER to R.string.expense_subcategory_private_transfer,
    ExpenseSubcategory.CAR_RENTAL to R.string.expense_subcategory_car_rental,
    ExpenseSubcategory.MOTORBIKE_RENTAL to R.string.expense_subcategory_motorbike_rental,
    ExpenseSubcategory.FUEL to R.string.expense_subcategory_fuel,
    ExpenseSubcategory.TOLLS_PARKING to R.string.expense_subcategory_tolls_parking,
    ExpenseSubcategory.FERRY_BOAT to R.string.expense_subcategory_ferry_boat,
    ExpenseSubcategory.PUBLIC_TRANSIT to R.string.expense_subcategory_public_transit,
    ExpenseSubcategory.RESTAURANT to R.string.expense_subcategory_restaurant,
    ExpenseSubcategory.STREET_FOOD to R.string.expense_subcategory_street_food,
    ExpenseSubcategory.GROCERIES_SUPERMARKET to R.string.expense_subcategory_groceries_supermarket,
    ExpenseSubcategory.CAFE_BREAKFAST to R.string.expense_subcategory_cafe_breakfast,
    ExpenseSubcategory.BAR_DRINKS to R.string.expense_subcategory_bar_drinks,
    ExpenseSubcategory.DELIVERY to R.string.expense_subcategory_delivery,
    ExpenseSubcategory.HOTEL to R.string.expense_subcategory_hotel,
    ExpenseSubcategory.HOSTEL to R.string.expense_subcategory_hostel,
    ExpenseSubcategory.VACATION_RENTAL to R.string.expense_subcategory_vacation_rental,
    ExpenseSubcategory.RESORT to R.string.expense_subcategory_resort,
    ExpenseSubcategory.CAMPING to R.string.expense_subcategory_camping,
    ExpenseSubcategory.HOMESTAY to R.string.expense_subcategory_homestay,
    ExpenseSubcategory.MUSEUM_CULTURE to R.string.expense_subcategory_museum_culture,
    ExpenseSubcategory.TOUR_EXCURSION to R.string.expense_subcategory_tour_excursion,
    ExpenseSubcategory.NATURE_PARK to R.string.expense_subcategory_nature_park,
    ExpenseSubcategory.WATER_SPORTS to R.string.expense_subcategory_water_sports,
    ExpenseSubcategory.ADVENTURE_SPORTS to R.string.expense_subcategory_adventure_sports,
    ExpenseSubcategory.SPA_WELLNESS to R.string.expense_subcategory_spa_wellness,
    ExpenseSubcategory.TICKETS_ATTRACTIONS to R.string.expense_subcategory_tickets_attractions,
    ExpenseSubcategory.CONCERT_FESTIVAL to R.string.expense_subcategory_concert_festival,
    ExpenseSubcategory.NIGHTLIFE_CLUB to R.string.expense_subcategory_nightlife_club,
    ExpenseSubcategory.CINEMA_THEATER to R.string.expense_subcategory_cinema_theater,
    ExpenseSubcategory.GAMES_ARCADE to R.string.expense_subcategory_games_arcade,
    ExpenseSubcategory.SPORTS_EVENT to R.string.expense_subcategory_sports_event,
    ExpenseSubcategory.CLOTHING to R.string.expense_subcategory_clothing,
    ExpenseSubcategory.SOUVENIRS_GIFTS to R.string.expense_subcategory_souvenirs_gifts,
    ExpenseSubcategory.ELECTRONICS to R.string.expense_subcategory_electronics,
    ExpenseSubcategory.PHARMACY_HEALTH to R.string.expense_subcategory_pharmacy_health,
    ExpenseSubcategory.CONVENIENCE_STORE to R.string.expense_subcategory_convenience_store,
    ExpenseSubcategory.TRAVEL_INSURANCE to R.string.expense_subcategory_travel_insurance,
    ExpenseSubcategory.MEDICAL_HEALTH to R.string.expense_subcategory_medical_health,
    ExpenseSubcategory.VEHICLE_INSURANCE to R.string.expense_subcategory_vehicle_insurance,
    ExpenseSubcategory.EQUIPMENT_INSURANCE to R.string.expense_subcategory_equipment_insurance,
    ExpenseSubcategory.TIPS_GRATUITIES to R.string.expense_subcategory_tips_gratuities,
    ExpenseSubcategory.SIM_COMMUNICATIONS to R.string.expense_subcategory_sim_communications,
    ExpenseSubcategory.LAUNDRY to R.string.expense_subcategory_laundry,
    ExpenseSubcategory.FEES_SURCHARGES to R.string.expense_subcategory_fees_surcharges,
    ExpenseSubcategory.UNSPECIFIED to R.string.expense_subcategory_unspecified
)

fun ExpenseSubcategory.toStringRes(): Int =
    subcategoryToStringResMap[this] ?: R.string.expense_subcategory_unspecified
