package es.pedrazamiguez.splittrip.features.authentication.presentation.feature

import androidx.activity.compose.LocalActivity
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.NoCredentialException
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import es.pedrazamiguez.splittrip.core.designsystem.navigation.LocalRootNavController
import es.pedrazamiguez.splittrip.core.designsystem.navigation.Routes
import es.pedrazamiguez.splittrip.core.logging.recordDiagnosticException
import es.pedrazamiguez.splittrip.features.authentication.presentation.component.CollisionMergeDialog
import es.pedrazamiguez.splittrip.features.authentication.presentation.model.AuthenticationUiEvent
import es.pedrazamiguez.splittrip.features.authentication.presentation.screen.LoginScreen
import es.pedrazamiguez.splittrip.features.authentication.presentation.viewmodel.AuthenticationViewModel
import kotlinx.coroutines.launch
import org.koin.androidx.compose.koinViewModel
import timber.log.Timber

@Suppress("LongMethod", "CognitiveComplexMethod") // Feature orchestrator with multi-action collection
@Composable
fun LoginFeature(
    viewModel: AuthenticationViewModel = koinViewModel<AuthenticationViewModel>(),
    onLoginSuccess: () -> Unit = {}
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
    val activity = LocalActivity.current
    val coroutineScope = rememberCoroutineScope()

    // default_web_client_id is generated by the google-services plugin in :app module.
    // At runtime, the merged resources include it, so we look it up by name.
    val webClientId = remember(activity) {
        activity?.let {
            val resId = it.resources.getIdentifier(
                "default_web_client_id",
                "string",
                it.packageName
            )
            if (resId != 0) it.getString(resId) else null
        }
    }

    LaunchedEffect(webClientId) {
        if (webClientId.isNullOrBlank()) {
            Timber.e("Google Sign-In webClientId (default_web_client_id) could not be resolved from resources")
        } else {
            Timber.d("Google Sign-In webClientId initialized successfully")
        }
    }

    val navController = LocalRootNavController.current

    LoginScreen(
        uiState = uiState,
        isGoogleSignInAvailable = true,
        onEvent = { event ->
            viewModel.onEvent(
                event,
                onLoginSuccess
            )
        },
        onForgotPasswordClick = {
            navController.navigate(Routes.FORGOT_PASSWORD)
        },
        onStartJourneyClick = {
            navController.navigate(Routes.REGISTER)
        },
        onGoogleSignInClick = {
            if (activity == null) {
                Timber.w("Activity is null during Google sign-in click")
                return@LoginScreen
            }
            if (webClientId.isNullOrBlank()) {
                val error = IllegalStateException(
                    "Google Sign-In webClientId (default_web_client_id) is missing or blank"
                )
                Timber.e(error, "Google sign-in clicked but webClientId is unavailable")
                recordDiagnosticException(
                    throwable = error,
                    customKeys = mapOf(
                        "auth_provider" to "google",
                        "credential_stage" to "web_client_id_resolution"
                    )
                )
                viewModel.onEvent(
                    AuthenticationUiEvent.GoogleSignInFailed,
                    onLoginSuccess
                )
                return@LoginScreen
            }
            coroutineScope.launch {
                try {
                    // Use GetSignInWithGoogleOption which provides the standard
                    // Google Sign-In bottom sheet UI, works reliably on all devices.
                    val signInWithGoogleOption = GetSignInWithGoogleOption.Builder(webClientId)
                        .build()

                    val request = GetCredentialRequest.Builder()
                        .addCredentialOption(signInWithGoogleOption)
                        .build()

                    val credentialManager = CredentialManager.create(activity)
                    val result = credentialManager.getCredential(
                        request = request,
                        context = activity
                    )

                    val googleIdTokenCredential = GoogleIdTokenCredential
                        .createFrom(result.credential.data)

                    viewModel.onEvent(
                        AuthenticationUiEvent.GoogleSignInResult(
                            idToken = googleIdTokenCredential.idToken
                        ),
                        onLoginSuccess
                    )
                } catch (e: GetCredentialCancellationException) {
                    Timber.w(e, "Google sign-in cancelled or aborted: type=${e.type}, message=${e.message}")
                } catch (e: NoCredentialException) {
                    Timber.w(e, "No Google accounts available on this device: message=${e.message}")
                    recordDiagnosticException(
                        throwable = e,
                        customKeys = mapOf(
                            "auth_provider" to "google",
                            "credential_stage" to "get_credential"
                        )
                    )
                    viewModel.onEvent(
                        AuthenticationUiEvent.GoogleSignInFailed,
                        onLoginSuccess
                    )
                } catch (e: Exception) {
                    Timber.e(e, "Google sign-in failed: type=${e.javaClass.simpleName}, message=${e.message}")
                    recordDiagnosticException(
                        throwable = e,
                        customKeys = mapOf(
                            "auth_provider" to "google",
                            "credential_stage" to "get_credential"
                        )
                    )
                    viewModel.onEvent(
                        AuthenticationUiEvent.GoogleSignInFailed,
                        onLoginSuccess
                    )
                }
            }
        },
        onContinueAsGuestClick = {
            viewModel.onEvent(AuthenticationUiEvent.ContinueAsGuest, onLoginSuccess)
        }
    )

    if (uiState.showCollisionDialog) {
        CollisionMergeDialog(
            uiState = uiState,
            onEvent = { event ->
                viewModel.onEvent(
                    event,
                    onLoginSuccess
                )
            }
        )
    }
}
