#!/usr/bin/env python3
import os
import re
import sys
import xml.etree.ElementTree as ET

# Try to import andaluh. If not present, fail gracefully with instructions.
try:
    import andaluh
except ImportError:
    print("Error: The 'andaluh' python package is required.")
    print("Please install it using: pip install andaluh --break-system-packages")
    sys.exit(1)

# Regex to match Android formatting placeholders: e.g. %s, %1$s, %02d, %%, etc.
# Non-capturing groups are used for parts of the placeholder, while the entire
# pattern is enclosed in a single capturing group so that re.split keeps it.
ANDROID_PLACEHOLDER_REGEX = re.compile(
    r'(%(?:[0-9]+\$)?[-#+ 0,(\<]?[0-9]*(?:\.[0-9]+)?(?:[tT][a-zA-Z]|[a-zA-Z%]))'
)

def escape_android_string(text):
    if not text:
        return text
    # Escape unescaped single quotes (') and double quotes (")
    # which are required to be escaped in Android XML resource files.
    text = re.sub(r"(?<!\\)'", r"\'", text)
    text = re.sub(r'(?<!\\)"', r'\"', text)
    return text

def translate_text(text):
    if not text:
        return text
    
    # Split text by Android placeholders
    tokens = ANDROID_PLACEHOLDER_REGEX.split(text)
    for i in range(len(tokens)):
        if i % 2 == 0:
            # Even indices are the plain text around placeholders.
            # Only translate if there is meaningful text to translate.
            # Preserve leading/trailing whitespace.
            orig_token = tokens[i]
            stripped = orig_token.strip()
            if stripped:
                translated = andaluh.epa(stripped)
                # Keep original leading/trailing whitespace
                leading = orig_token[:len(orig_token) - len(orig_token.lstrip())]
                trailing = orig_token[len(orig_token.rstrip()):]
                tokens[i] = leading + translated + trailing
        else:
            # Odd indices are placeholders (e.g. %1$s). Preserve them.
            pass
            
    # Reassemble and escape quotes
    return escape_android_string("".join(tokens))

def translate_node(node):
    # Skip nodes that are explicitly marked as not translatable
    if node.attrib.get('translatable') == 'false':
        return
        
    if node.text:
        node.text = translate_text(node.text)
    for child in node:
        translate_node(child)
        if child.tail:
            child.tail = translate_text(child.tail)

def process_file(src_path, dest_path):
    print(f"Translating: {src_path} -> {dest_path}")
    
    # Parse the source XML
    tree = ET.parse(src_path)
    root = tree.getroot()
    
    # Translate all string/item values
    translate_node(root)
    
    # Insert automated generation warning comment at the top of the root element
    # Check if there is already our comment, if not insert it.
    comment_text = " This file is automatically generated by generateAndaluzStrings. Do not edit manually. "
    has_comment = False
    for child in list(root):
        # In ElementTree, comments are elements where child.tag is ET.Comment
        if child.tag == ET.Comment and child.text == comment_text:
            has_comment = True
            break
    if not has_comment:
        root.insert(0, ET.Comment(comment_text))
        
    # Ensure proper indentation
    ET.indent(root, space="    ")
    
    # Write to destination
    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
    tree.write(dest_path, encoding="utf-8", xml_declaration=True)

def main():
    # Scan all directories in the project root
    project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    for root_dir, dirs, files in os.walk(project_dir):
        # Skip build and hidden directories (like .git, .gradle)
        if "build" in root_dir or "/." in root_dir:
            continue
            
        for file in files:
            if file == "strings.xml":
                parent_dir = os.path.basename(root_dir)
                if parent_dir == "values-es":
                    src_path = os.path.join(root_dir, file)
                    dest_dir = os.path.join(os.path.dirname(root_dir), "values-es-rAN")
                    dest_path = os.path.join(dest_dir, file)
                    process_file(src_path, dest_path)

if __name__ == "__main__":
    main()
